### ISSUE TITLE
Messaging for Result Value and Result Detection Condition

### ISSUE THREAD

**Issue by patrickleclair-GORDONFN** [gordonfn/schema#14]
When a result value and a result detection condition are both present the current schema issues a **OneOf** error. Could this be changed to better reflect the actual error? 

New Text Example:

**Only one of ResultValue or ResultDetectionConditon may exist**

**Comment by willfarrell** [comment]
I'm waiting for https://github.com/ajv-validator/ajv-errors/issues/81 before resolving this.
