### ISSUE TITLE
add an export tidy data format

### ISSUE THREAD

**Issue by CamMakoJ** [gordonfn/schema#25]
hopefully, this is the right spot to request this, but i noticed when exporting data it doesn't follow tidy principles in that the variable 'Characteristic Name' contains many different types of observations. This makes it difficult to use the data cleanly in a GIS environment as a .csv and requires pre-processing.

**Comment by willfarrell** [comment]
Hi Cam, this is as good as any place for your question. These are the tidy principles I'm familiar with:

1. Each variable must have its own column.
1. Each observation must have its own row.
1. Each value must have its own cell.

We do follow this with our schema. From my understanding of your question, you're expecting a sample (a collection of observations at a certain point in space-time) to be at the observation level and having each characteristic (and their observation level metadata) be classified as variables. In that case, you would need multiple columns for each characteristic to ensure the observation metadata is preserved. With over 300 different characteristics in use on our platform, and support for over 14000, this easily balloons into hundreds of thousands of columns. You can imagine the technology limitations that arise from processing, storing, and searching the data when it's in this format.

We are working on a tool to allow the downloading and filtering of the data across datasets via the browser. We already offer an API with the functionality if that approach is preferred. This should help with pre-processing needed to remove unused characteristics and improve performance when pivoting the data into your specific format.

Is there a specific standard/specification you're transforming the data into? A feature to allow downloading the data in alternative formats has been sitting in our idea pile for quite some time, but haven't heard of much interest in it.

**Comment by CamMakoJ** [comment]
Totally makes sense - it's easy to focus on the 9 parameters I'm interested in and ignore the thousands of others. You make a good point about tidy data, and I think in that case your schema makes sense for the reasons you mentioned

If there was a way however as mentioned to export specific parameters as rows that would be nice - will need to check out the API and test that out.

**Comment by willfarrell** [comment]
You can find our API documentation here: https://github.com/gordonfn/api
