### ISSUE TITLE
Remove trailing whitespace from WQX domain values

### ISSUE THREAD

**Issue by marykruk** [gordonfn/schema#38]

**Comment by willfarrell** [comment]
|** Trailing Whitespace: "Benzamide, 2,6-difluoro-N-[[[3-methyl-4-[(1,1,2,2-tetrafluoroethyl)thio]phenyl]amino]carbonyl]- "
|** Trailing Whitespace: "Benzamide, N-[[[2-bromo-4-[(1,1,2,2-tetrafluoroethyl)thio]phenyl]amino]carbonyl]-2,6-difluoro- "
|** Trailing Whitespace: "Benzene, 1-[1-bromo-2,2,2-trifluoro-1-(trifluoromethyl)ethyl]-2-methoxy- "
|** Trailing Whitespace: "Carbamic acid, N-(3-nitrophenyl)-, 2,2,3,3-tetrafluoropropyl ester "
|** Trailing Whitespace: "Cyclopropane, 1,1,2,2,3,3-hexafluoro-  "
|** Trailing Whitespace: "Deoxycylindrospermopsin "
|** Trailing Whitespace: "Ethanamine, 1,1,2,2-tetrafluoro-N,N-dimethyl-  "
|** Trailing Whitespace: "Ethanesulfonic acid, 1,1,2,2-tetrafluoro-  "
|** Trailing Whitespace: "Perfluorodecanesulfonic acid "
|** Trailing Whitespace: "Propane, 1,1,1,2,3,3-hexafluoro-3-(2,2,2-trifluoroethoxy)-  "

**Comment by willfarrell** [comment]
Seems to only affect chars we don't use

**Comment by marykruk** [comment]
@willfarrell What about `Sulfonates, alkyl-, linear `? that was the one that gave me an error in testing

**Comment by willfarrell** [comment]
I'm not seeing whitespace on that one while building

**Comment by willfarrell** [comment]
MonitoringLocationHorizontalCoordinateReferenceSystem
|-> Skip additions
|-> Skip deprecated
|-> Skip subset
|-> Skip subtractions
|-> Skip deprecated
MonitoringLocationHorizontalAccuracyUnit
|-> Override '% saturatn**' with '% saturatn'
|-> Override 'gpm**' with 'gpm'
|-> Skip additions
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
MonitoringLocationVerticalUnit
|-> Override '% saturatn**' with '% saturatn'
|-> Override 'gpm**' with 'gpm'
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
MonitoringLocationType
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
ActivityType
|-> Skip deprecated
|-> Skip subset
|-> Skip deprecated
|-> Subtracting 24 items
ActivityGroupType
|-> Skip additions
|-> Skip deprecated
|-> Skip subset
|-> Skip subtractions
|-> Skip deprecated
ActivityMediaName
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
ActivityDepthHeightUnit
|-> Override '% saturatn**' with '% saturatn'
|-> Override 'gpm**' with 'gpm'
|-> Skip additions
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
SampleCollectionEquipmentName
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
CharacteristicName
|** Retired Duplicates: "1,2-Benzenedicarboxamide, N2-[1,1-dimethyl-2-(methylsulfonyl)ethyl]-3-iodo-N1-[2-methyl-4-[1,2,2,2-tetrafluoro-1-(trifluoromethyl)ethyl]phenyl]-", "1-Decanesulfonic acid, 3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,10-heptadecafluoro-", "1-Octanesulfonamide, 1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,8-heptadecafluoro-", "Heptanoic acid, 2,2,3,3,4,4,5,5,6,6,7,7,7-tridecafluoro-", "Hexadecanoic acid, 2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13,14,14,15,15,16,16,16-hentriacontafluoro-", "Nonanoic acid, 2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,9-heptadecafluoro-", "Octadecanoic acid, 2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13,14,14,15,15,16,16,17,17,18,18,18-pentatriacontafluoro-", "Pentanoic acid, 2,2,3,3,4,4,5,5,5-nonafluoro-"
|-> Skip deprecated
|** Trailing Whitespace: "Benzamide, 2,6-difluoro-N-[[[3-methyl-4-[(1,1,2,2-tetrafluoroethyl)thio]phenyl]amino]carbonyl]- "
|** Trailing Whitespace: "Benzamide, N-[[[2-bromo-4-[(1,1,2,2-tetrafluoroethyl)thio]phenyl]amino]carbonyl]-2,6-difluoro- "
|** Trailing Whitespace: "Benzene, 1-[1-bromo-2,2,2-trifluoro-1-(trifluoromethyl)ethyl]-2-methoxy- "
|** Trailing Whitespace: "Carbamic acid, N-(3-nitrophenyl)-, 2,2,3,3-tetrafluoropropyl ester "
|** Trailing Whitespace: "Cyclopropane, 1,1,2,2,3,3-hexafluoro-  "
|** Trailing Whitespace: "Deoxycylindrospermopsin "
|** Trailing Whitespace: "Ethanamine, 1,1,2,2-tetrafluoro-N,N-dimethyl-  "
|** Trailing Whitespace: "Ethanesulfonic acid, 1,1,2,2-tetrafluoro-  "
|** Trailing Whitespace: "Perfluorodecanesulfonic acid "
|** Trailing Whitespace: "Propane, 1,1,1,2,3,3-hexafluoro-3-(2,2,2-trifluoroethoxy)-  "
|** Subset value missing from allowed values: CharacteristicName "BDE-126"
|** Subset value missing from allowed values: CharacteristicName "BDE-183"
|** Subset value missing from allowed values: CharacteristicName "BDE-206"
|** Subset value missing from allowed values: CharacteristicName "BDE-49"
|** Subset value missing from allowed values: CharacteristicName "BDE-71"
|** Subset value missing from allowed values: CharacteristicName "BDE-77"
|** Subset value missing from allowed values: CharacteristicName "Sulfonates, alkyl-, linear "
|-> Skip subtractions
|-> Subtracting 664 items
MethodSpeciation
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
ResultSampleFraction
|-> Skip deprecated
|-> Skip subset
|-> Skip deprecated
|-> Subtracting 10 items
ResultUnit
|-> Override '% saturatn**' with '% saturatn'
|-> Override 'gpm**' with 'gpm'
|** Subset value missing from allowed values: ResultUnit "HU"
|-> Skip subtractions
|-> Skip deprecated
ResultValueType
|-> Skip deprecated
|-> Skip subset
|-> Skip deprecated
|-> Subtracting 1 items
ResultDetectionCondition
|-> Skip deprecated
|-> Skip deprecated
|-> Subtracting 2 items
ResultDetectionQuantitationLimitUnit
|-> Override '% saturatn**' with '% saturatn'
|-> Override 'gpm**' with 'gpm'
|** Subset value missing from allowed values: ResultDetectionQuantitationLimitUnit "HU"
|-> Skip subtractions
|-> Skip deprecated
ResultDetectionQuantitationLimitType
|-> Skip additions
|-> Skip deprecated
|** Subset value missing from allowed values: ResultDetectionQuantitationLimitType "Reporting Limit"
|-> Skip subtractions
|-> Skip deprecated
ResultStatusID
|-> Skip additions
|-> Skip deprecated
|-> Skip subtractions
|-> Skip deprecated
ResultAnalyticalMethodContext
|-> Skip deprecated
|-> Skip subset
|-> Skip deprecated
|-> Subtracting 21 items
CharacteristicNameGroups Not Assigned .beta.-Heptachlor epoxide
CharacteristicNameGroups Not Assigned 2,3,4,5- & 2,3,5,6- Tetrachlorophenol
CharacteristicNameGroups Not Assigned 2,4- & 2,5-Dichlorophenol
CharacteristicNameGroups Not Assigned 2,4,6-Trinitro-5-tert-butyl-m-xylene
CharacteristicNameGroups Not Assigned 4-Nonylphenol pentaethoxylates
CharacteristicNameGroups Not Assigned 4-Nonylphenol tetraethoxylates
CharacteristicNameGroups Not Assigned 4-Nonylphenol triethoxylate
CharacteristicNameGroups Not Assigned Acesulfame
CharacteristicNameGroups Not Assigned Amoxicillin
CharacteristicNameGroups Not Assigned Aspartame
CharacteristicNameGroups Not Assigned Aspirin
CharacteristicNameGroups Not Assigned C4-Fluorenes
CharacteristicNameGroups Not Assigned Carbaryl-d7
CharacteristicNameGroups Not Assigned Cashmeran
CharacteristicNameGroups Not Assigned Clindamycin
CharacteristicNameGroups Not Assigned Clofibric acid
CharacteristicNameGroups Not Assigned Clothianidin-d3
CharacteristicNameGroups Not Assigned Cocaine
CharacteristicNameGroups Not Assigned Cyclamate
CharacteristicNameGroups Not Assigned Cyhalothrin
CharacteristicNameGroups Not Assigned Dibenzo[a,h]pyrene
CharacteristicNameGroups Not Assigned Dinitramine
CharacteristicNameGroups Not Assigned Distance From Left Bank
CharacteristicNameGroups Not Assigned EPTC-d14
CharacteristicNameGroups Not Assigned Fenoprofen
CharacteristicNameGroups Not Assigned Fenoxaprop-P-ethyl
CharacteristicNameGroups Not Assigned Flonicamid
CharacteristicNameGroups Not Assigned Fludioxonil
CharacteristicNameGroups Not Assigned Fluoxetine
CharacteristicNameGroups Not Assigned Glufosinate
CharacteristicNameGroups Not Assigned Indomethacin
CharacteristicNameGroups Not Assigned Linuron-d6
CharacteristicNameGroups Not Assigned m- & p-Chlorophenol
CharacteristicNameGroups Not Assigned Meclofenamic acid
CharacteristicNameGroups Not Assigned Methamphetamine
CharacteristicNameGroups Not Assigned Metolachlor-d6
CharacteristicNameGroups Not Assigned Musk moskine
CharacteristicNameGroups Not Assigned Musk Tibetene
CharacteristicNameGroups Not Assigned Neotame
CharacteristicNameGroups Not Assigned Norfluoxetine
CharacteristicNameGroups Not Assigned Ofloxacin
CharacteristicNameGroups Not Assigned Oxolinic acid
CharacteristicNameGroups Not Assigned oxygen isotopes of water (d18O)
CharacteristicNameGroups Not Assigned Parathion-d10
CharacteristicNameGroups Not Assigned Pentoxifylline
CharacteristicNameGroups Not Assigned Phenolics
CharacteristicNameGroups Not Assigned Phorate-d10
CharacteristicNameGroups Not Assigned Phycocyanin
CharacteristicNameGroups Not Assigned Pirimicarb
CharacteristicNameGroups Not Assigned Prothioconazole
CharacteristicNameGroups Not Assigned Pyridaben
CharacteristicNameGroups Not Assigned Quinclorac
CharacteristicNameGroups Not Assigned Retene
CharacteristicNameGroups Not Assigned Saccharin
CharacteristicNameGroups Not Assigned Spirotetramat
CharacteristicNameGroups Not Assigned Sucralose
CharacteristicNameGroups Not Assigned Sulfoxaflor
CharacteristicNameGroups Not Assigned Thorium
CharacteristicNameGroups Not Assigned Tolfenamic acid
CharacteristicNameGroups Not Assigned Traseolide
CharacteristicNameGroups Not Assigned Trihalomethanes
CharacteristicNameGroups Not Assigned Trinexapac-Ethyl
